name: Light and Sound
favicon: null
layout_spectrum: 0.24789
typography_spectrum: 0.97308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.75
  lightness: 0.3072000350803137
  saturation: 0.8125
  rhythmicContrast: 0.5106338986661285
purpose: []
